export default [
  {
    picture: 'story-01.jpg',
    alt: 'historia 1',
    title: 'Me duele abrazarte',
    teller: '@sopita_d_letras',
    hashtag: '#medueleabrazarte',
    team: 'RED - TEAM 6',
    members: [
      'Alexia Jessica Melissa Pacheco Pérez',
      'América Paola Noriega Ríos',
      'Jesús Jordán Correa Barragán',
      'Vianney Berenice Carranza Martínez',
      'Juan Manuel Vela Quintero',
    ],
  },
  {
    picture: 'story-02.jpg',
    alt: 'historia 2',
    title: 'La realidad detrás de la industria del Fast Fashion',
    teller: 'PENDIENTE',
    hashtag:
      '#Lusademoda #Mihistoriadeprenda #LusaShuinlomasin #moda #fastfashion #maquilas #explotación #modarápida #ambiente #fashion',
    team: 'BROWN - TEAM 1',
    members: [
      'Alejandra Escobedo Leos',
      'Alejandra Jiménez Mayo',
      'Franceska Aranzazu parra Ibarra',
      'Karime Gisselle Carvajal Gámez',
    ],
  },
  {
    picture: 'story-03.jpg',
    alt: 'historia 3',
    title: 'Malas lenguas',
    teller: '@andrea09as',
    hashtag: '#ElBullyingMata #MalasLenguasHiloteca',
    team: 'GREEN - TEAM 9',
    members: [
      'Jordán Adrián Cuellar Martínez',
      'Denisse Aracely Esquivel Rodríguez',
      'Danna Paola García Navarro',
      'Adriana Nohemí García Martínez',
      'Paulina Garza Garza',
      'Emilia Rojas Murguía',
    ],
  },
  {
    picture: 'story-04.jpg',
    alt: 'historia 4',
    title: 'Futbol en el Ring',
    teller: '@rossbelt12',
    hashtag: '#ElFutbolNOesViolencia',
    team: 'RED - TEAM 4',
    members: [
      'Rossbelt Adrián Fernández Galindo',
      'Aedmy Zuzeth Briones García',
      'Sydney Puente Rubio',
      'Emilio Escamilla Adame',
    ],
  },
  {
    picture: 'story-05.jpg',
    alt: 'historia 5',
    title: '07-10-22 WHAT IF',
    teller: '@Bheobukheli',
    hashtag: '#UnaRealidadDeCuento',
    team: 'GREEN - TEAM 7',
    members: [
      'Alondra Miranda López Acuña',
      'Ana Fabiola Carrillo Villarreal',
      'Fernando Rubén Guerra Villarreal',
    ],
  },
  {
    picture: 'story-06.jpg',
    alt: 'historia 6',
    title: 'La flor Smeraldo',
    teller: 'PENDIENTE',
    hashtag: '#LFS',
    team: 'ORANGE - TEAM 2',
    members: [
      'Cesar Adrián Zermeño Soto',
      'Alondra Maribel Becerra Marín',
      'Andrea Cristina Sánchez García',
      'Diego Enrique Miranda Córdoba',
      'Hanna Luisa Plata Martínez',
      'Vanessa Córdova Gutiérrez',
    ],
  },
];
